# Generated by Django 5.1.15 on 2026-09-07 15:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0009_apitoken_expires_at'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OAuthClient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_id', models.CharField(help_text='Public identifier issued at registration; travels in every authorize / token request', max_length=64, unique=True)),
                ('client_name', models.CharField(help_text='Name the client supplied at registration, shown on the consent screen', max_length=120)),
                ('redirect_uris', models.JSONField(default=list, help_text='Exact redirect URIs the client registered; an authorize request may use only these')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='When the client registered itself')),
                ('last_used_at', models.DateTimeField(blank=True, help_text='Last time this client completed a token exchange; null until first use', null=True)),
            ],
            options={
                'verbose_name': 'OAuth client',
                'verbose_name_plural': 'OAuth clients',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OAuthAuthorizationCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code_hash', models.CharField(help_text='SHA-256 digest of the one-time code; the code itself is never stored', max_length=64, unique=True)),
                ('redirect_uri', models.CharField(help_text='Redirect URI used in the authorize request; the token exchange must repeat it exactly', max_length=500)),
                ('code_challenge', models.CharField(help_text='PKCE challenge (S256) the client committed to; the verifier is checked against it', max_length=128)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='When the code was issued')),
                ('expires_at', models.DateTimeField(help_text='Hard expiry; an exchange after this instant is refused')),
                ('consumed_at', models.DateTimeField(blank=True, help_text='When the code was exchanged; a second exchange is refused', null=True)),
                ('user', models.ForeignKey(help_text='User who approved the consent screen; tokens minted from this code act as them', on_delete=django.db.models.deletion.CASCADE, related_name='oauth_authorization_codes', to=settings.AUTH_USER_MODEL)),
                ('client', models.ForeignKey(help_text='Client the code was issued to; the token exchange must present the same one', on_delete=django.db.models.deletion.CASCADE, related_name='authorization_codes', to='mcp.oauthclient')),
            ],
            options={
                'verbose_name': 'OAuth authorization code',
                'verbose_name_plural': 'OAuth authorization codes',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['code_hash'], name='mcp_oauthau_code_ha_cb62df_idx')],
            },
        ),
        migrations.CreateModel(
            name='OAuthRefreshToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token_hash', models.CharField(help_text='SHA-256 digest of the refresh secret; the secret itself is never stored', max_length=64, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='When the refresh token was issued')),
                ('replaced_at', models.DateTimeField(blank=True, help_text='When rotation superseded this token; a replaced token is refused', null=True)),
                ('revoked_at', models.DateTimeField(blank=True, help_text='When the grant was revoked; revoking the access token revokes this too', null=True)),
                ('access_token', models.ForeignKey(help_text='Access token most recently issued from this refresh token', on_delete=django.db.models.deletion.CASCADE, related_name='oauth_refresh_tokens', to='accounts.apitoken')),
                ('client', models.ForeignKey(help_text='Client the refresh token belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='refresh_tokens', to='mcp.oauthclient')),
                ('user', models.ForeignKey(help_text='User the refreshed access tokens will act as', on_delete=django.db.models.deletion.CASCADE, related_name='oauth_refresh_tokens', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'OAuth refresh token',
                'verbose_name_plural': 'OAuth refresh tokens',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['token_hash'], name='mcp_oauthre_token_h_717553_idx')],
            },
        ),
    ]
