# Generated by Django 5.1.15 on 2026-05-15 15:36

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("workspaces", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Project",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(help_text="Display name of the project", max_length=120)),
                ("description", models.TextField(blank=True, help_text="Project description in Markdown. Optional")),
                (
                    "slug_prefix",
                    models.CharField(
                        help_text="Short uppercase identifier used in task references, e.g. HRW in HRW-49. Immutable in practice",
                        max_length=6,
                        validators=[
                            django.core.validators.RegexValidator(
                                message="Slug prefix must be 2–6 uppercase Latin letters.", regex="^[A-Z]{2,6}$"
                            )
                        ],
                    ),
                ),
                (
                    "next_task_number",
                    models.PositiveIntegerField(
                        default=1, help_text="Counter for the next task to be created in this project. Auto-incremented"
                    ),
                ),
                (
                    "archived",
                    models.BooleanField(
                        default=False,
                        help_text="Archived projects are hidden by default but retain their tasks and history",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, help_text="When the project was created")),
                (
                    "workspace",
                    models.ForeignKey(
                        help_text="Workspace this project belongs to",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="projects",
                        to="workspaces.workspace",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ProjectUpdate",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "health",
                    models.CharField(
                        choices=[
                            ("on_track", "On track"),
                            ("at_risk", "At risk"),
                            ("off_track", "Off track"),
                            ("completed", "Completed"),
                        ],
                        help_text="Current health signal of the project as judged by the author",
                        max_length=12,
                    ),
                ),
                ("body", models.TextField(help_text="Update body in Markdown")),
                ("created_at", models.DateTimeField(auto_now_add=True, help_text="When the update was posted")),
                ("updated_at", models.DateTimeField(auto_now=True, help_text="When the update was last edited")),
                (
                    "author",
                    models.ForeignKey(
                        help_text="User who wrote the update",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="project_updates",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        help_text="Project this status update is about",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="updates",
                        to="projects.project",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddConstraint(
            model_name="project",
            constraint=models.UniqueConstraint(
                fields=("workspace", "slug_prefix"), name="projects_unique_workspace_slug_prefix"
            ),
        ),
    ]
