# Generated by Django 5.1.15 on 2026-05-16 18:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="project",
            options={"verbose_name": "Project", "verbose_name_plural": "Projects"},
        ),
        migrations.AlterModelOptions(
            name="projectupdate",
            options={
                "ordering": ["-created_at"],
                "verbose_name": "Project update",
                "verbose_name_plural": "Project updates",
            },
        ),
        migrations.AddField(
            model_name="project",
            name="icon",
            field=models.CharField(
                blank=True,
                help_text="Lucide icon name shown next to the project in the sidebar and lists. Optional",
                max_length=40,
            ),
        ),
        migrations.AddField(
            model_name="project",
            name="lead",
            field=models.ForeignKey(
                blank=True,
                help_text="Single user responsible for the project's direction. Implicit member",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="led_projects",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="project",
            name="members",
            field=models.ManyToManyField(
                blank=True,
                help_text="Contributors who work on the project. Opt-in list used for 'My Projects' filters and the subscriber set for project updates. Not enforced on Task.assignee — any workspace member can still be assigned a task",
                related_name="project_memberships",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
