# Generated by Django 5.1.15 on 2026-05-18 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0002_alter_project_options_alter_projectupdate_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="icon_color",
            field=models.CharField(
                blank=True,
                help_text="Accent colour token for the project icon. One of the curated palette keys (``blue``, ``violet``, ``amber``, ``emerald``, ``rose``, ``sky``, ``orange``, ``zinc``). Empty string falls back to the neutral subtle-foreground tint",
                max_length=12,
            ),
        ),
    ]
