# Generated by Django 5.1.15 on 2026-05-22 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_add_project_icon_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='wip_limits',
            field=models.JSONField(blank=True, default=dict, help_text='Per-status work-in-progress limits for the kanban board, as a {status_key: max_cards} map. Absent / 0 means no limit. Drives the column N/limit fraction + capacity bar + over-limit warning'),
        ),
    ]
