# Generated by Django 5.1.15 on 2026-05-22 16:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0004_project_wip_limits'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='wip_limits',
        ),
    ]
