# Generated by Django 5.1.15 on 2026-05-31 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0005_remove_project_wip_limits'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectupdate',
            name='stats',
            field=models.JSONField(blank=True, default=dict, help_text="Frozen task-counter snapshot when the author opted into 'Include stats since last update' at compose time. Empty dict when the toggle was off. Shape: ``{since, until, closed, in_progress, in_review, planned, ready}``; the snapshot stays correct even after underlying tasks change or are deleted"),
        ),
    ]
