# Generated by Django 5.1.15 on 2026-05-31 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0006_projectupdate_stats'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='notify_members_only',
            field=models.BooleanField(default=False, help_text='When true, project status updates fan out only to ``members`` (plus the ``lead``) instead of every workspace member. Off by default to preserve the existing workspace-wide audience; admins can flip it on private boards'),
        ),
    ]
