# Generated by Django 5.1.15 on 2026-10-06 07:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0007_project_notify_members_only'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='projectupdate',
            options={'ordering': ['-created_at', '-id'], 'verbose_name': 'Project update', 'verbose_name_plural': 'Project updates'},
        ),
    ]
