# Generated by Django 5.1.15 on 2026-05-15 15:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("projects", "0001_initial"),
        ("workspaces", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ActivityLog",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "target_type",
                    models.CharField(
                        help_text="Kind of object the event is about: task, comment, project, workspace, or member",
                        max_length=20,
                    ),
                ),
                (
                    "target_id",
                    models.PositiveBigIntegerField(
                        help_text="ID of the target object. Not a foreign key — the row survives target deletion"
                    ),
                ),
                (
                    "event_type",
                    models.CharField(
                        help_text="Event category, e.g. task.status_changed, comment.created, member.role_changed",
                        max_length=40,
                    ),
                ),
                (
                    "payload",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Event-specific details as JSON: diffs, denormalized snapshots, metadata",
                    ),
                ),
                (
                    "bulk_id",
                    models.UUIDField(
                        blank=True,
                        db_index=True,
                        help_text="Shared by all events emitted from a single bulk operation. Null for one-off events",
                        null=True,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        db_index=True,
                        help_text="When the event was recorded. Always sort timelines by this column, never by id",
                    ),
                ),
                (
                    "actor",
                    models.ForeignKey(
                        blank=True,
                        help_text="User who performed the action. Always set from request.user — never inferred. Null for system-initiated events",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="activity",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        blank=True,
                        help_text="Project this event relates to, if applicable",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="activity",
                        to="projects.project",
                    ),
                ),
                (
                    "workspace",
                    models.ForeignKey(
                        help_text="Workspace this event occurred in. Denormalized for fast feed filtering",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="activity",
                        to="workspaces.workspace",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(fields=["workspace", "-created_at"], name="activity_ac_workspa_d5a040_idx"),
                    models.Index(
                        fields=["target_type", "target_id", "-created_at"], name="activity_ac_target__b87fe4_idx"
                    ),
                ],
            },
        ),
    ]
