# Generated by Django 5.1.15 on 2026-05-18 16:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("activity", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="activitylog",
            options={
                "ordering": ["-created_at"],
                "verbose_name": "Activity log entry",
                "verbose_name_plural": "Activity log",
            },
        ),
    ]
