# Generated by Django 5.1.15 on 2026-09-05 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0003_alter_activitylog_target_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activitylog',
            name='target_type',
            field=models.CharField(help_text='Kind of object the event is about: task, comment, project, workspace, member, attachment, or meeting', max_length=20),
        ),
    ]
