# Generated by Django 5.1.15 on 2026-10-06 07:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0004_alter_activitylog_target_type'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='activitylog',
            options={'ordering': ['-created_at', '-id'], 'verbose_name': 'Activity log entry', 'verbose_name_plural': 'Activity log'},
        ),
    ]
