# Generated by Django 5.1.15 on 2026-10-06 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0005_alter_activitylog_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activitylog',
            name='target_type',
            field=models.CharField(help_text='Kind of object the event is about: task, comment, project, workspace, member, attachment, meeting, or milestone', max_length=20),
        ),
    ]
