# Generated by Django 5.1.15 on 2026-05-15 15:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("labels", "0001_initial"),
        ("projects", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Task",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "number",
                    models.PositiveIntegerField(
                        help_text="Sequential number within the project; combined with the project's slug prefix forms the user-facing ID (e.g. HRW-49)"
                    ),
                ),
                (
                    "title",
                    models.CharField(help_text="Short title shown in lists and the kanban board", max_length=200),
                ),
                ("description", models.TextField(blank=True, help_text="Full description in Markdown")),
                (
                    "status",
                    models.CharField(
                        default="to-do",
                        help_text="Workflow state: one of planned, to-do, in-progress, in-review, done",
                        max_length=20,
                    ),
                ),
                (
                    "priority",
                    models.SmallIntegerField(
                        choices=[(0, "No priority"), (1, "Urgent"), (2, "High"), (3, "Medium"), (4, "Low")],
                        default=0,
                        help_text="Task priority. 0 = no priority, 1 = urgent, 4 = low",
                    ),
                ),
                (
                    "size",
                    models.SmallIntegerField(
                        blank=True,
                        choices=[(1, "1"), (2, "2"), (3, "3"), (5, "5"), (8, "8"), (13, "13")],
                        help_text="Story-point estimate. Restricted to the Fibonacci set 1, 2, 3, 5, 8, 13",
                        null=True,
                    ),
                ),
                (
                    "due_date",
                    models.DateField(blank=True, help_text="Optional deadline (date only, no time-of-day)", null=True),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, help_text="When the task was created")),
                ("updated_at", models.DateTimeField(auto_now=True, help_text="When the task was last modified")),
                (
                    "assignee",
                    models.ForeignKey(
                        blank=True,
                        help_text="User responsible for completing the task",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="assigned_tasks",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "labels",
                    models.ManyToManyField(
                        blank=True, help_text="Labels attached to the task", related_name="tasks", to="labels.label"
                    ),
                ),
                (
                    "parent",
                    models.ForeignKey(
                        blank=True,
                        help_text="Parent task if this is a subtask. Depth limited to one level",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="subtasks",
                        to="tasks.task",
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        help_text="Project this task belongs to",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tasks",
                        to="projects.project",
                    ),
                ),
                (
                    "reporter",
                    models.ForeignKey(
                        help_text="User who created the task. Set automatically from request.user",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="reported_tasks",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-updated_at"],
                "indexes": [
                    models.Index(fields=["project", "status"], name="tasks_task_project_b78682_idx"),
                    models.Index(fields=["project", "-updated_at"], name="tasks_task_project_e037b3_idx"),
                    models.Index(fields=["assignee", "status"], name="tasks_task_assigne_7928f6_idx"),
                ],
                "constraints": [
                    models.UniqueConstraint(fields=("project", "number"), name="tasks_unique_project_number")
                ],
            },
        ),
    ]
