# Generated by Django 5.1.15 on 2026-05-17 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tasks", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="task",
            name="archived_at",
            field=models.DateTimeField(
                blank=True,
                db_index=True,
                help_text="Timestamp when the task was archived. Orthogonal to status: an archived task keeps its original status (typically done) so unarchiving restores the prior state. Archived tasks are hidden from default views — Show archived toggle in the sidebar brings them back, and ?xstatus / explicit filters still apply",
                null=True,
            ),
        ),
    ]
