# Generated by Django 5.1.15 on 2026-05-17 11:10

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("labels", "0002_label_color_validator"),
        ("projects", "0002_alter_project_options_alter_projectupdate_options_and_more"),
        ("tasks", "0002_task_archived_at"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name="task",
            index=models.Index(fields=["-updated_at"], name="tasks_task_updated_1e52d9_idx"),
        ),
        migrations.AddIndex(
            model_name="task",
            index=models.Index(fields=["due_date"], name="tasks_task_due_dat_bce847_idx"),
        ),
        migrations.AddIndex(
            model_name="task",
            index=models.Index(fields=["priority", "-updated_at"], name="tasks_task_priorit_cb8cdb_idx"),
        ),
        migrations.AddIndex(
            model_name="task",
            index=models.Index(fields=["size"], name="tasks_task_size_b251e8_idx"),
        ),
        migrations.AddIndex(
            model_name="task",
            index=models.Index(
                condition=models.Q(("archived_at__isnull", True)),
                fields=["status", "-updated_at"],
                name="tasks_active_status_updated",
            ),
        ),
        migrations.AddIndex(
            model_name="task",
            index=models.Index(
                condition=models.Q(("archived_at__isnull", True)),
                fields=["assignee", "-updated_at"],
                name="tasks_active_assignee_updated",
            ),
        ),
    ]
