# Generated by Django 5.1.15 on 2026-05-20 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0003_task_sort_and_dashboard_indexes'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='blocks',
            field=models.ManyToManyField(blank=True, help_text='Tasks that cannot start until this one is done (directional). Reverse side is blocked_by', related_name='blocked_by', to='tasks.task'),
        ),
        migrations.AddField(
            model_name='task',
            name='related',
            field=models.ManyToManyField(blank=True, help_text='Tasks related to this one without a blocking dependency (symmetric)', to='tasks.task'),
        ),
    ]
