# Generated by Django 5.1.15 on 2026-05-21 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0004_task_blocks_task_related'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='start_date',
            field=models.DateField(blank=True, help_text='Work start date. Auto-set to today on first transition to in-progress when null', null=True),
        ),
    ]
