# Generated by Django 5.1.15 on 2026-05-22 17:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cycles', '0001_initial'),
        ('tasks', '0006_alter_task_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='cycle',
            field=models.ForeignKey(blank=True, help_text='Workspace cycle (time-box) this task is committed to; null means backlog', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tasks', to='cycles.cycle'),
        ),
    ]
