# Generated by Django 5.1.15 on 2026-05-22 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0008_alter_task_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(default='planned', help_text='Workflow state: one of planned, ready, to-do, in-progress, in-review, done, cancelled', max_length=20),
        ),
    ]
