# Generated by Django 5.1.15 on 2026-05-24 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0009_alter_task_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='completed_at',
            field=models.DateTimeField(blank=True, db_index=True, help_text='Timestamp when the task entered the done status; cleared when it leaves done. Maintained in save() and the bulk update path. Powers the completed-date filter', null=True),
        ),
    ]
