# Generated by Django 5.1.15 on 2026-06-08 16:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cycles', '0002_cycle_end_notified_at_cycle_start_notified_at'),
        ('labels', '0004_label_position_for_dnd'),
        ('projects', '0007_project_notify_members_only'),
        ('recurring', '0001_initial'),
        ('tasks', '0012_task_end_date'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='occurrence_date',
            field=models.DateField(blank=True, help_text='The scheduled occurrence date this task was generated for; null for normal tasks. Unique per recurrence for idempotent generation', null=True),
        ),
        migrations.AddField(
            model_name='task',
            name='recurrence',
            field=models.ForeignKey(blank=True, help_text="Recurring-task rule that spawned this task; null for normal tasks. SET_NULL so the task survives the rule's deletion", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='instances', to='recurring.recurringtask'),
        ),
        migrations.AlterField(
            model_name='task',
            name='due_date',
            field=models.DateField(blank=True, help_text='Hard deadline (a marker, not the bar end). Late when end_date or today is past it', null=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, help_text='When the task was last modified. ``auto_now`` fires on ``.save()``; the bulk UPDATE path sets this column explicitly (see ``apps.tasks.bulk``) so it stays correct when ``save()`` is bypassed for batched writes'),
        ),
        migrations.AddConstraint(
            model_name='task',
            constraint=models.UniqueConstraint(condition=models.Q(('recurrence__isnull', False)), fields=('recurrence', 'occurrence_date'), name='tasks_unique_recurrence_occurrence'),
        ),
    ]
