# Generated by Django 5.1.15 on 2026-10-02 09:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0013_task_occurrence_date_task_recurrence_and_more'),
        ('workspaces', '0009_alter_workspace_slug'),
    ]

    operations = [
        migrations.CreateModel(
            name='TaskEmbedding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vector', models.BinaryField(help_text='Normalised float32 vector, little-endian, as produced by the embedding model')),
                ('dimensions', models.PositiveSmallIntegerField(help_text='Length of the vector, so a mismatched model is caught before the dot product')),
                ('model', models.CharField(help_text='Embedding model that produced this vector; rows from other models are ignored', max_length=120)),
                ('text_hash', models.CharField(help_text='SHA-256 of the text that was embedded, so unchanged tasks are not re-sent', max_length=64)),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='When the vector was last rebuilt; also stamps the in-process matrix cache')),
                ('task', models.OneToOneField(help_text='Task this vector describes', on_delete=django.db.models.deletion.CASCADE, related_name='embedding', to='tasks.task')),
                ('workspace', models.ForeignKey(help_text="Denormalised from the task's project so one query loads a whole workspace", on_delete=django.db.models.deletion.CASCADE, related_name='task_embeddings', to='workspaces.workspace')),
            ],
            options={
                'verbose_name': 'task embedding',
                'verbose_name_plural': 'task embeddings',
                'indexes': [models.Index(fields=['workspace', 'model'], name='tasks_taske_workspa_4246c5_idx')],
            },
        ),
    ]
