# Generated by Django 5.1.15 on 2026-10-02 15:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0014_taskembedding'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='epic',
            field=models.ForeignKey(blank=True, help_text="Epic this task belongs to. Deliberately separate from parent: a subtask keeps its parent and may still belong to an epic, and an epic collects across the whole workspace while a parent must share its child's project", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='epic_tasks', to='tasks.task'),
        ),
        migrations.AddField(
            model_name='task',
            name='kind',
            field=models.CharField(default='task', help_text='Whether this row is work (task) or collects work (epic)', max_length=8),
        ),
    ]
