# Generated by Django 5.1.15 on 2026-10-06 06:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('milestones', '0001_initial'),
        ('tasks', '0015_epics'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='milestone',
            field=models.ForeignKey(blank=True, help_text="Milestone this task is committed to. At most one, and only one whose scope includes this task's project — membership is chosen, never inferred from dates", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tasks', to='milestones.milestone'),
        ),
    ]
