# Generated by Django 5.1.15 on 2026-10-08 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0016_task_milestone'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='size_source',
            field=models.CharField(blank=True, choices=[('human', 'Person'), ('agent', 'Agent')], help_text='Who put the estimate there: a person, or an agent that guessed it. Null when there is no estimate, and on estimates predating this field', max_length=10, null=True),
        ),
    ]
