# Generated by Django 5.1.15 on 2026-10-09 15:47

import django.contrib.postgres.indexes
from django.conf import settings
from django.contrib.postgres.operations import TrigramExtension
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cycles', '0002_cycle_end_notified_at_cycle_start_notified_at'),
        ('labels', '0004_label_position_for_dnd'),
        ('milestones', '0001_initial'),
        ('projects', '0008_alter_projectupdate_options'),
        ('recurring', '0001_initial'),
        ('tasks', '0017_task_size_source'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        # The index below needs ``gin_trgm_ops``, which the extension
        # provides — so it has to be installed first. CREATE EXTENSION
        # wants a superuser; on a deployment where the app's database
        # user is not one, run it by hand as the owner before migrating.
        TrigramExtension(),
        migrations.AddIndex(
            model_name='task',
            index=django.contrib.postgres.indexes.GinIndex(fields=['title'], name='tasks_title_trigram', opclasses=['gin_trgm_ops']),
        ),
    ]
