# Generated by Django 5.1.15 on 2026-05-15 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="language",
            field=models.CharField(
                blank=True,
                choices=[("en", "English"), ("uk", "Ukrainian")],
                help_text="Preferred UI language. Overrides browser cookie and Accept-Language",
                max_length=8,
            ),
        ),
    ]
