# Generated by Django 5.1.15 on 2026-05-18 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0003_alter_user_options"),
        ("projects", "0003_add_project_icon_color"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="favourite_projects",
            field=models.ManyToManyField(
                blank=True,
                help_text="Projects this user has starred for quick access. The sidebar nav lists only these (with an empty-state CTA when the set is empty); the project list page renders a toggle star on every card to maintain the set",
                related_name="favourited_by",
                to="projects.project",
            ),
        ),
    ]
