# Generated by Django 5.1.15 on 2026-05-19 12:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0004_add_user_favourite_projects"),
    ]

    operations = [
        migrations.CreateModel(
            name="ApiToken",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "name",
                    models.CharField(
                        help_text="Human-readable label set by the user when minting the token", max_length=80
                    ),
                ),
                (
                    "token_hash",
                    models.CharField(
                        help_text="SHA-256 hex digest of the plain secret; the secret itself is never stored",
                        max_length=64,
                        unique=True,
                    ),
                ),
                (
                    "prefix",
                    models.CharField(
                        help_text="First 8 chars of the plain secret, kept so the user can identify tokens in the UI",
                        max_length=8,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, help_text="When the token was generated")),
                (
                    "last_used_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="Last successful authentication with this token; null until first use",
                        null=True,
                    ),
                ),
                (
                    "revoked_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="When the user (or an admin) revoked the token; revoked tokens fail authentication",
                        null=True,
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        help_text="Owner of the token; the token authenticates as this user",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="api_tokens",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "API token",
                "verbose_name_plural": "API tokens",
                "ordering": ["-created_at"],
                "indexes": [models.Index(fields=["token_hash"], name="accounts_ap_token_h_008738_idx")],
            },
        ),
    ]
