# Generated by Django 5.1.15 on 2026-05-21 19:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_apitoken'),
        ('workspaces', '0003_workspaceinvite'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='active_workspace',
            field=models.ForeignKey(blank=True, help_text="Workspace the user is currently scoped into. The sidebar switcher sets it; All Tasks / Projects / My Work / Inbox / My Activity are filtered to it. Null falls back to the user's first workspace by name", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='workspaces.workspace'),
        ),
    ]
