# Generated by Django 5.1.15 on 2026-05-22 09:05

import apps.accounts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_user_active_workspace'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='avatar',
            field=models.ImageField(blank=True, help_text='Profile photo, square-cropped and resized to JPEG on upload; falls back to a colour-initial circle when unset', max_length=255, null=True, upload_to=apps.accounts.models.avatar_upload_to),
        ),
    ]
