# Generated by Django 5.1.15 on 2026-05-31 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_user_avatar'),
        ('tasks', '0012_task_end_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='favourite_tasks',
            field=models.ManyToManyField(blank=True, help_text="Tasks this user has starred for quick access. The sidebar nav surfaces them either nested under their (starred) project or in a separate Issues section when the project itself isn't starred. Task detail page exposes the toggle", related_name='favourited_by_users', to='tasks.task'),
        ),
    ]
