# Generated by Django 5.1.15 on 2026-09-07 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_user_favourite_tasks'),
    ]

    operations = [
        migrations.AddField(
            model_name='apitoken',
            name='expires_at',
            field=models.DateTimeField(blank=True, help_text='Hard expiry; null means the token never expires. Set on OAuth-issued tokens, left null on ones the user pasted by hand', null=True),
        ),
    ]
