# Generated by Django 5.1.15 on 2026-10-06 06:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projects', '0007_project_notify_members_only'),
        ('workspaces', '0010_epics_toggle'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Milestone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Short name shown in lists, pickers and on the timeline marker', max_length=120)),
                ('goal', models.CharField(blank=True, help_text='One line saying what must be true when this is reached', max_length=200)),
                ('description', models.TextField(blank=True, help_text='Longer notes; the goal line is what the plan shows')),
                ('target_date', models.DateField(help_text='The date the work aims at; a milestone has no duration')),
                ('closed_at', models.DateTimeField(blank=True, help_text='When a person closed it; closing is an action, every other state is derived', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='When the milestone was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='When the milestone was last edited')),
                ('owner', models.ForeignKey(blank=True, help_text='Person answerable for the date; optional', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='owned_milestones', to=settings.AUTH_USER_MODEL)),
                ('projects', models.ManyToManyField(help_text='Projects aiming at this date; a task may only join from a project listed here', related_name='milestones', to='projects.project')),
                ('workspace', models.ForeignKey(help_text='Workspace this milestone belongs to; its projects must all be in it', on_delete=django.db.models.deletion.CASCADE, related_name='milestones', to='workspaces.workspace')),
            ],
            options={
                'verbose_name': 'Milestone',
                'verbose_name_plural': 'Milestones',
                'ordering': ['target_date', 'id'],
                'indexes': [models.Index(fields=['workspace', 'target_date'], name='milestones__workspa_ebe842_idx')],
                'constraints': [models.UniqueConstraint(fields=('workspace', 'name'), name='milestones_unique_workspace_name')],
            },
        ),
    ]
