# Generated by Django 5.1.15 on 2026-05-20 21:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('comments', '0003_comment_parent_comment_project_update_and_more'),
        ('projects', '0003_add_project_icon_color'),
        ('tasks', '0004_task_blocks_task_related'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Reaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emoji', models.CharField(help_text='The reacted emoji as a Unicode grapheme (may be a multi-codepoint ZWJ sequence)', max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='When the reaction was added')),
                ('comment', models.ForeignKey(blank=True, help_text='Comment this reaction is on. Null when it targets a task or a project update', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reactions', to='comments.comment')),
                ('project_update', models.ForeignKey(blank=True, help_text='Project update this reaction is on. Null when it targets a task or a comment', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reactions', to='projects.projectupdate')),
                ('task', models.ForeignKey(blank=True, help_text='Task this reaction is on. Null when it targets a comment or a project update', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reactions', to='tasks.task')),
                ('user', models.ForeignKey(help_text='User who reacted', on_delete=django.db.models.deletion.CASCADE, related_name='reactions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Reaction',
                'verbose_name_plural': 'Reactions',
                'ordering': ['created_at'],
                'constraints': [models.CheckConstraint(condition=models.Q(models.Q(('comment__isnull', True), ('project_update__isnull', True), ('task__isnull', False)), models.Q(('comment__isnull', False), ('project_update__isnull', True), ('task__isnull', True)), models.Q(('comment__isnull', True), ('project_update__isnull', False), ('task__isnull', True)), _connector='OR'), name='reaction_exactly_one_target'), models.UniqueConstraint(condition=models.Q(('task__isnull', False)), fields=('user', 'task', 'emoji'), name='reaction_unique_user_task_emoji'), models.UniqueConstraint(condition=models.Q(('comment__isnull', False)), fields=('user', 'comment', 'emoji'), name='reaction_unique_user_comment_emoji'), models.UniqueConstraint(condition=models.Q(('project_update__isnull', False)), fields=('user', 'project_update', 'emoji'), name='reaction_unique_user_update_emoji')],
            },
        ),
    ]
