# Generated by Django 5.1.15 on 2026-05-22 07:46

import apps.attachments.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('comments', '0003_comment_parent_comment_project_update_and_more'),
        ('projects', '0003_add_project_icon_color'),
        ('tasks', '0005_task_start_date'),
        ('workspaces', '0003_workspaceinvite'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Attachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('file', 'File attachment'), ('inline_image', 'Inline editor image')], default='file', help_text='Whether this is a panel file attachment or an image embedded in a description editor', max_length=20)),
                ('file', models.FileField(help_text='The stored file, written under MEDIA_ROOT and served only through the auth-gated download view', max_length=255, upload_to=apps.attachments.models.attachment_upload_to)),
                ('original_name', models.CharField(help_text='Original client-supplied filename, shown in the UI and used for the download name', max_length=255)),
                ('content_type', models.CharField(help_text='Sniffed MIME type of the stored file, set on upload and trusted thereafter', max_length=120)),
                ('size', models.PositiveBigIntegerField(help_text='Stored file size in bytes, after image normalization when applicable')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='When the file was uploaded')),
                ('comment', models.ForeignKey(blank=True, help_text='Comment this file is attached to. Null when it targets a task or a project', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='comments.comment')),
                ('project', models.ForeignKey(blank=True, help_text='Project whose description embeds this inline image. Null when it targets a task or a comment', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='projects.project')),
                ('task', models.ForeignKey(blank=True, help_text='Task this file is attached to. Null when it targets a comment or a project', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='tasks.task')),
                ('uploader', models.ForeignKey(help_text='User who uploaded the file. Null after that user is deleted', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_attachments', to=settings.AUTH_USER_MODEL)),
                ('workspace', models.ForeignKey(help_text='Workspace this file belongs to. Denormalized for access-control filtering and path scoping', on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='workspaces.workspace')),
            ],
            options={
                'verbose_name': 'Attachment',
                'verbose_name_plural': 'Attachments',
                'ordering': ['created_at'],
                'indexes': [models.Index(fields=['workspace', 'kind'], name='attachments_workspa_44e236_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(models.Q(('comment__isnull', True), ('project__isnull', True), ('task__isnull', False)), models.Q(('comment__isnull', False), ('project__isnull', True), ('task__isnull', True)), models.Q(('comment__isnull', True), ('project__isnull', False), ('task__isnull', True)), _connector='OR'), name='attachment_exactly_one_owner')],
            },
        ),
    ]
