# Generated by Django 5.1.15 on 2026-05-22 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attachments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='attachment',
            name='content_hash',
            field=models.CharField(blank=True, db_index=True, help_text='SHA-256 of the stored bytes; rows sharing a hash share one blob on disk (dedup)', max_length=64),
        ),
    ]
