# Generated by Django 5.1.15 on 2026-06-08 16:26

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('labels', '0004_label_position_for_dnd'),
        ('projects', '0007_project_notify_members_only'),
        ('workspaces', '0008_workspace_member_defaults'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RecurringTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Title copied onto each generated task', max_length=200)),
                ('description', models.TextField(blank=True, help_text='Markdown body copied onto each generated task')),
                ('priority', models.SmallIntegerField(default=0, help_text='Priority copied onto each generated task (0=none, 1=Urgent … 4=Low)')),
                ('size', models.SmallIntegerField(blank=True, help_text='Fibonacci size estimate copied onto each generated task; blank leaves it unset', null=True)),
                ('freq', models.CharField(choices=[('daily', 'Daily'), ('weekly', 'Weekly'), ('monthly', 'Monthly')], default='weekly', help_text='Recurrence frequency: daily, weekly, or monthly', max_length=10)),
                ('interval', models.PositiveSmallIntegerField(default=1, help_text='Repeat every N units of freq (e.g. 2 + weekly = every two weeks)', validators=[django.core.validators.MinValueValidator(1)])),
                ('weekdays', models.JSONField(blank=True, default=list, help_text="For weekly freq: weekdays to fire on as ints (0=Mon … 6=Sun); empty falls back to start_date's weekday")),
                ('day_of_month', models.PositiveSmallIntegerField(blank=True, help_text="For monthly freq: day of month (1-31, clamped to month length); blank uses start_date's day", null=True)),
                ('start_date', models.DateField(help_text='Anchor date; the first occurrence is the first matching date on or after this')),
                ('lead_time_days', models.PositiveSmallIntegerField(default=0, help_text='Create each task this many days before its occurrence date (0 = on the day)')),
                ('end_mode', models.CharField(choices=[('never', 'Never'), ('on_date', 'On date'), ('after_count', 'After N occurrences')], default='never', help_text='When the rule stops: never, on a date, or after a number of occurrences', max_length=12)),
                ('end_date', models.DateField(blank=True, help_text='Last date an occurrence may fall on, when end_mode is on_date', null=True)),
                ('max_occurrences', models.PositiveIntegerField(blank=True, help_text='Stop after this many occurrences, when end_mode is after_count', null=True)),
                ('occurrences_created', models.PositiveIntegerField(default=0, help_text='How many tasks this rule has spawned so far')),
                ('next_occurrence_date', models.DateField(blank=True, help_text='Cursor: date of the next task to spawn; null when the rule is finished', null=True)),
                ('last_spawned_at', models.DateTimeField(blank=True, help_text='When the materializer last created a task from this rule', null=True)),
                ('is_active', models.BooleanField(default=True, help_text='Paused rules and finished rules (cursor exhausted) skip materialization')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='When the rule was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='When the rule was last edited or advanced')),
                ('assignee', models.ForeignKey(blank=True, help_text='Assignee copied onto each generated task; blank leaves them unassigned', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recurring_assigned', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(blank=True, help_text='Who created the rule; used as the reporter on generated tasks', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recurring_created', to=settings.AUTH_USER_MODEL)),
                ('labels', models.ManyToManyField(blank=True, help_text='Labels copied onto each generated task', related_name='recurring_tasks', to='labels.label')),
                ('project', models.ForeignKey(help_text='Project new tasks are created in', on_delete=django.db.models.deletion.CASCADE, related_name='recurring_tasks', to='projects.project')),
                ('workspace', models.ForeignKey(help_text='Workspace the rule belongs to; denormalized from project for the recurring-tasks list scope', on_delete=django.db.models.deletion.CASCADE, related_name='recurring_tasks', to='workspaces.workspace')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['is_active', 'next_occurrence_date'], name='recurring_r_is_acti_c9bc63_idx')],
            },
        ),
    ]
