# Generated by Django 5.1.15 on 2026-05-15 15:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("workspaces", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="LabelGroup",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "name",
                    models.CharField(
                        help_text='Group name shown in label pickers (e.g. "Type", "Priority", "Area")', max_length=60
                    ),
                ),
                (
                    "is_exclusive",
                    models.BooleanField(
                        default=False, help_text="If true, a task can have at most one label from this group"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, help_text="When the group was created")),
                (
                    "workspace",
                    models.ForeignKey(
                        help_text="Workspace this group belongs to",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="label_groups",
                        to="workspaces.workspace",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Label",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(help_text="Label display name", max_length=60)),
                ("color", models.CharField(help_text="Hex color code (#RRGGBB or #RRGGBBAA)", max_length=9)),
                ("created_at", models.DateTimeField(auto_now_add=True, help_text="When the label was created")),
                (
                    "workspace",
                    models.ForeignKey(
                        help_text="Workspace this label belongs to",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="labels",
                        to="workspaces.workspace",
                    ),
                ),
                (
                    "group",
                    models.ForeignKey(
                        blank=True,
                        help_text="Optional group this label is part of",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="labels",
                        to="labels.labelgroup",
                    ),
                ),
            ],
        ),
        migrations.AddConstraint(
            model_name="labelgroup",
            constraint=models.UniqueConstraint(fields=("workspace", "name"), name="labels_group_unique_workspace_name"),
        ),
        migrations.AddConstraint(
            model_name="label",
            constraint=models.UniqueConstraint(fields=("workspace", "name"), name="labels_unique_workspace_name"),
        ),
    ]
