# Generated by Django 5.1.15 on 2026-05-16 06:36

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("labels", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="label",
            options={"verbose_name": "Label", "verbose_name_plural": "Labels"},
        ),
        migrations.AlterModelOptions(
            name="labelgroup",
            options={"verbose_name": "Label group", "verbose_name_plural": "Label groups"},
        ),
        migrations.AlterField(
            model_name="label",
            name="color",
            field=models.CharField(
                help_text="Hex color code (#RRGGBB or #RRGGBBAA). Required — labels must be visually distinguishable",
                max_length=9,
                validators=[
                    django.core.validators.RegexValidator(
                        message="Color must be a hex code: #RRGGBB or #RRGGBBAA (e.g. #a855f7 for purple).",
                        regex="^#(?:[0-9a-fA-F]{6}|[0-9a-fA-F]{8})$",
                    )
                ],
            ),
        ),
    ]
