# Generated by Django 5.1.15 on 2026-05-28 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('labels', '0003_labelgroup_description_seed_defaults'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='label',
            options={'ordering': ['position', 'name'], 'verbose_name': 'Label', 'verbose_name_plural': 'Labels'},
        ),
        migrations.AddField(
            model_name='label',
            name='position',
            field=models.IntegerField(default=0, help_text="Sort order within the label's group (or within the ungrouped list when ``group`` is null). Lower comes first. Driven by the labels-management drag-drop reorder; values are dense per ``(group, workspace)`` slice."),
        ),
    ]
