# Generated by Django 5.1.15 on 2026-05-22 17:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('workspaces', '0005_workspace_cycle_settings'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cycle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.PositiveIntegerField(help_text="1-based index of the cycle's time window since the cadence anchor; forms the label Cycle N")),
                ('name', models.CharField(blank=True, help_text='Optional custom name; falls back to Cycle N when empty', max_length=120)),
                ('start_date', models.DateField(help_text='First day of the cycle (inclusive)')),
                ('end_date', models.DateField(help_text='Last day of the cycle (inclusive)')),
                ('status', models.CharField(choices=[('planning', 'Planning'), ('active', 'Active'), ('completed', 'Completed')], default='planning', help_text='Lifecycle state derived from today vs the cycle bounds: planning, active, or completed', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='When the cycle row was materialized')),
                ('completed_at', models.DateTimeField(blank=True, help_text='When the cycle first transitioned to completed; frozen once set', null=True)),
                ('workspace', models.ForeignKey(help_text='Workspace this cycle belongs to; cadence is shared across all its projects', on_delete=django.db.models.deletion.CASCADE, related_name='cycles', to='workspaces.workspace')),
            ],
            options={
                'verbose_name': 'Cycle',
                'verbose_name_plural': 'Cycles',
                'ordering': ['-start_date'],
                'indexes': [models.Index(fields=['workspace', 'status'], name='cycles_cycl_workspa_ac6d80_idx')],
                'constraints': [models.UniqueConstraint(fields=('workspace', 'number'), name='cycles_unique_workspace_number')],
            },
        ),
    ]
