# Generated by Django 5.1.15 on 2026-05-22 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cycles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cycle',
            name='end_notified_at',
            field=models.DateTimeField(blank=True, help_text='When the cycle-ending-soon notification was fanned out; stamped once to stay idempotent', null=True),
        ),
        migrations.AddField(
            model_name='cycle',
            name='start_notified_at',
            field=models.DateTimeField(blank=True, help_text='When the cycle-started notification was fanned out; stamped once to stay idempotent', null=True),
        ),
    ]
