from django.conf import settings
from django.core.validators import MinValueValidator
from django.db import models
from django.utils.translation import gettext_lazy as _

# Weekday labels keyed by ``datetime.date.weekday()`` (0 = Monday … 6 =
# Sunday). Used both for the ``weekdays`` JSON values and the
# human-readable cadence summary.
WEEKDAY_LABELS = {
    0: _("Mon"),
    1: _("Tue"),
    2: _("Wed"),
    3: _("Thu"),
    4: _("Fri"),
    5: _("Sat"),
    6: _("Sun"),
}


class RecurringTask(models.Model):
    """A rule that spawns real :class:`~apps.tasks.models.Task` rows on a cadence.

    This is the *template*, not a task: it holds the blueprint copied onto
    each generated task (title, description, assignee, priority, size,
    labels) plus the recurrence rule (frequency + interval, optional
    weekdays for weekly, day-of-month for monthly) and a cursor
    (``next_occurrence_date``) the materializer advances.

    Tasks are generated by :func:`apps.recurring.services.materialize_due`
    on a daily schedule — independent of whether the previous occurrence
    was completed (the agreed "by schedule" model). Each generated task
    links back via ``Task.recurrence``. See ADR 0028.

    Weekday convention: ``weekdays`` is a list of ints matching
    :meth:`datetime.date.weekday` (0 = Monday … 6 = Sunday).
    """

    class Freq(models.TextChoices):
        DAILY = "daily", _("Daily")
        WEEKLY = "weekly", _("Weekly")
        MONTHLY = "monthly", _("Monthly")

    class EndMode(models.TextChoices):
        NEVER = "never", _("Never")
        ON_DATE = "on_date", _("On date")
        AFTER_COUNT = "after_count", _("After N occurrences")

    workspace = models.ForeignKey(
        "workspaces.Workspace",
        on_delete=models.CASCADE,
        related_name="recurring_tasks",
        help_text="Workspace the rule belongs to; denormalized from project for the recurring-tasks list scope",
    )
    project = models.ForeignKey(
        "projects.Project",
        on_delete=models.CASCADE,
        related_name="recurring_tasks",
        help_text="Project new tasks are created in",
    )
    title = models.CharField(
        max_length=200,
        help_text="Title copied onto each generated task",
    )
    description = models.TextField(
        blank=True,
        help_text="Markdown body copied onto each generated task",
    )
    assignee = models.ForeignKey(
        settings.AUTH_USER_MODEL,
        on_delete=models.SET_NULL,
        null=True,
        blank=True,
        related_name="recurring_assigned",
        help_text="Assignee copied onto each generated task; blank leaves them unassigned",
    )
    priority = models.SmallIntegerField(
        default=0,
        help_text="Priority copied onto each generated task (0=none, 1=Urgent … 4=Low)",
    )
    size = models.SmallIntegerField(
        null=True,
        blank=True,
        help_text="Fibonacci size estimate copied onto each generated task; blank leaves it unset",
    )
    labels = models.ManyToManyField(
        "labels.Label",
        blank=True,
        related_name="recurring_tasks",
        help_text="Labels copied onto each generated task",
    )
    freq = models.CharField(
        max_length=10,
        choices=Freq.choices,
        default=Freq.WEEKLY,
        help_text="Recurrence frequency: daily, weekly, or monthly",
    )
    interval = models.PositiveSmallIntegerField(
        default=1,
        validators=[
            MinValueValidator(1),
        ],
        help_text="Repeat every N units of freq (e.g. 2 + weekly = every two weeks)",
    )
    weekdays = models.JSONField(
        default=list,
        blank=True,
        help_text="Weekly: weekdays to fire on as ints (0=Mon … 6=Sun); empty uses start_date's weekday",
    )
    day_of_month = models.PositiveSmallIntegerField(
        null=True,
        blank=True,
        help_text="For monthly freq: day of month (1-31, clamped to month length); blank uses start_date's day",
    )
    start_date = models.DateField(
        help_text="Anchor date; the first occurrence is the first matching date on or after this",
    )
    lead_time_days = models.PositiveSmallIntegerField(
        default=0,
        help_text="Create each task this many days before its occurrence date (0 = on the day)",
    )
    end_mode = models.CharField(
        max_length=12,
        choices=EndMode.choices,
        default=EndMode.NEVER,
        help_text="When the rule stops: never, on a date, or after a number of occurrences",
    )
    end_date = models.DateField(
        null=True,
        blank=True,
        help_text="Last date an occurrence may fall on, when end_mode is on_date",
    )
    max_occurrences = models.PositiveIntegerField(
        null=True,
        blank=True,
        help_text="Stop after this many occurrences, when end_mode is after_count",
    )
    occurrences_created = models.PositiveIntegerField(
        default=0,
        help_text="How many tasks this rule has spawned so far",
    )
    next_occurrence_date = models.DateField(
        null=True,
        blank=True,
        help_text="Cursor: date of the next task to spawn; null when the rule is finished",
    )
    last_spawned_at = models.DateTimeField(
        null=True,
        blank=True,
        help_text="When the materializer last created a task from this rule",
    )
    is_active = models.BooleanField(
        default=True,
        help_text="Paused rules and finished rules (cursor exhausted) skip materialization",
    )
    created_by = models.ForeignKey(
        settings.AUTH_USER_MODEL,
        on_delete=models.SET_NULL,
        null=True,
        blank=True,
        related_name="recurring_created",
        help_text="Who created the rule; used as the reporter on generated tasks",
    )
    created_at = models.DateTimeField(
        auto_now_add=True,
        help_text="When the rule was created",
    )
    updated_at = models.DateTimeField(
        auto_now=True,
        help_text="When the rule was last edited or advanced",
    )

    class Meta:
        ordering = [
            "-created_at",
        ]
        indexes = [
            models.Index(
                fields=[
                    "is_active",
                    "next_occurrence_date",
                ],
            ),
        ]

    def save(self, *args, **kwargs):
        """Seed the occurrence cursor on first save, then persist.

        A fresh, active rule with no cursor gets ``next_occurrence_date``
        set to its first occurrence on or after ``start_date`` so the
        materializer picks it up immediately. An already-running rule's
        cursor is never recomputed here — editing the schedule resets it
        explicitly through the form/service (Phase 2).
        """
        if self.next_occurrence_date is None and self.occurrences_created == 0 and self.is_active:
            from apps.recurring import services

            self.next_occurrence_date = services.initial_next_occurrence(self)
        super().save(*args, **kwargs)

    def __str__(self) -> str:
        """Return the rule's title and cadence summary."""
        return f"{self.title} ({self.human_cadence()})"

    def human_cadence(self) -> str:
        """Return a short human-readable description of the recurrence.

        Examples: ``"Daily"``, ``"Every 2 weeks on Mon, Wed"``,
        ``"Every 3 months on day 15"``. Used in the admin and the
        recurring-tasks list.

        Returns:
            A translated cadence string.
        """
        every = "" if self.interval == 1 else f"{self.interval} "
        if self.freq == self.Freq.DAILY:
            return _("Daily") if self.interval == 1 else _("Every %(n)s days") % {"n": self.interval}
        if self.freq == self.Freq.WEEKLY:
            base = _("Weekly") if self.interval == 1 else _("Every %(every)sweeks") % {"every": every}
            if self.weekdays:
                days = ", ".join(str(WEEKDAY_LABELS[d]) for d in sorted(self.weekdays) if d in WEEKDAY_LABELS)
                return _("%(base)s on %(days)s") % {"base": base, "days": days}
            return base
        base = _("Monthly") if self.interval == 1 else _("Every %(every)smonths") % {"every": every}
        dom = self.day_of_month or self.start_date.day
        return _("%(base)s on day %(dom)s") % {"base": base, "dom": dom}
