# Generated by Django 5.1.15 on 2026-05-18 16:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("comments", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="comment",
            options={"ordering": ["created_at"], "verbose_name": "Comment", "verbose_name_plural": "Comments"},
        ),
    ]
