# Generated by Django 5.1.15 on 2026-05-20 18:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0002_alter_comment_options'),
        ('projects', '0003_add_project_icon_color'),
        ('tasks', '0004_task_blocks_task_related'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='parent',
            field=models.ForeignKey(blank=True, help_text='Parent comment when this is a one-level reply; null for top-level comments', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='comments.comment'),
        ),
        migrations.AddField(
            model_name='comment',
            name='project_update',
            field=models.ForeignKey(blank=True, help_text='Project update this comment is attached to. Null when it targets a task', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='projects.projectupdate'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='task',
            field=models.ForeignKey(blank=True, help_text='Task this comment is attached to. Null when it targets a project update', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='tasks.task'),
        ),
        migrations.AddConstraint(
            model_name='comment',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('project_update__isnull', True), ('task__isnull', False)), models.Q(('project_update__isnull', False), ('task__isnull', True)), _connector='OR'), name='comment_exactly_one_target'),
        ),
    ]
