# Generated by Django 5.1.15 on 2026-06-10 13:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0003_comment_parent_comment_project_update_and_more'),
        ('meetings', '0001_initial'),
        ('projects', '0007_project_notify_members_only'),
        ('tasks', '0013_task_occurrence_date_task_recurrence_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='comment',
            name='comment_exactly_one_target',
        ),
        migrations.AddField(
            model_name='comment',
            name='meeting',
            field=models.ForeignKey(blank=True, help_text='Meeting this comment is attached to. Null when it targets a task or project update', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='meetings.meeting'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='project_update',
            field=models.ForeignKey(blank=True, help_text='Project update this comment is attached to. Null when it targets a task or meeting', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='projects.projectupdate'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='task',
            field=models.ForeignKey(blank=True, help_text='Task this comment is attached to. Null when it targets a project update or meeting', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='tasks.task'),
        ),
        migrations.AddConstraint(
            model_name='comment',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('meeting__isnull', True), ('project_update__isnull', True), ('task__isnull', False)), models.Q(('meeting__isnull', True), ('project_update__isnull', False), ('task__isnull', True)), models.Q(('meeting__isnull', False), ('project_update__isnull', True), ('task__isnull', True)), _connector='OR'), name='comment_exactly_one_target'),
        ),
    ]
