# Generated by Django 5.1.15 on 2026-10-06 07:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0004_remove_comment_comment_exactly_one_target_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ['created_at', 'id'], 'verbose_name': 'Comment', 'verbose_name_plural': 'Comments'},
        ),
    ]
