"""Lucide-icon template tag — inline SVG rendering.

Drop ``{% lucide "folder" %}`` (with optional ``"w-4 h-4 …"`` Tailwind
class) into a template; expands to the SVG markup at server-render
time. Replaces the ``<i data-lucide="folder">`` placeholders that the
CDN-loaded ``lucide.min.js`` used to swap out client-side.

Why move off the JS replacement: any in-place DOM swap (HTMX, SSE
peer-update) brings the ``<i>`` back, leaving a single-frame blank
spot until ``lucide.createIcons()`` reruns. Inline SVG renders with
the surrounding HTML — no race, no flash, no JS dependency for
icons.

Source dataset: ``apps/web/lucide_icons.json``, generated by
``scripts/extract_lucide.py`` from the ``lucide-static`` npm
package. Regenerate via ``make extract-icons`` when bumping the
package or pulling in new icons.

Unknown names fall back to ``DEFAULT_ICON`` so a stale or malicious
``project.icon`` value can't break a page — at worst, the user sees
the fallback glyph until they pick a real one.
"""

from __future__ import annotations

import json
from pathlib import Path
import re
from typing import Final

from django import template
from django.utils.safestring import mark_safe

register = template.Library()

# Resolve the JSON file once at module import. ~810 KB, ~1500 icons,
# Python loads it into a dict in <10 ms.
_ICONS_PATH: Final[Path] = Path(__file__).resolve().parent.parent / "lucide_icons.json"
_ICONS: Final[dict[str, str]] = json.loads(_ICONS_PATH.read_text())

DEFAULT_ICON: Final[str] = "circle-dashed"

# Lucide ships SVGs with ``class="lucide lucide-<name>"``. We rewrite
# this single attribute to the Tailwind class string the caller
# passes (``w-4 h-4 text-zinc-500`` etc.), then return as-is.
_CLASS_PATTERN: Final[re.Pattern[str]] = re.compile(r'\sclass="lucide lucide-[^"]+"')


@register.simple_tag
def lucide(name: str, css_class: str = "w-4 h-4") -> str:
    """Render an inline Lucide SVG.

    Args:
        name: Icon slug, e.g. ``"folder"``. Unknown slugs fall back
            to :data:`DEFAULT_ICON` so the template still renders.
        css_class: Tailwind / custom classes for sizing + colour.
            Defaults to ``"w-4 h-4"`` (16×16 currentColor).

    Returns:
        Safe SVG markup ready to drop into a template.
    """
    svg = _ICONS.get(name) or _ICONS[DEFAULT_ICON]
    return mark_safe(_CLASS_PATTERN.sub(f' class="{css_class}"', svg, count=1))


def has_icon(name: str) -> bool:
    """Return whether ``name`` exists in the loaded icon set.

    Useful for forms that accept user-entered icon slugs — validate
    server-side instead of trusting the picker UI alone.
    """
    return name in _ICONS
