"""Lucide-icon template tag — sprite-backed SVG rendering.

Drop ``{% lucide "folder" %}`` (with optional ``"w-4 h-4 …"`` Tailwind
class) into a template; expands to a minimal ``<svg><use
href="…/lucide.svg#lu-folder"/></svg>`` wrapper that pulls the path
from a browser-cacheable sprite shipped at ``static/sprites/lucide.svg``.

Why move off per-call inline SVG (Wave 4 sprite migration): every
``{% lucide %}`` previously expanded to ~280 B of SVG markup at server
render. On heavy pages (e.g. ``/tasks/?view=table`` with 260 tasks)
this was ~600-1500 invocations × 280 B = ~150-400 KB of repeated
markup. The sprite ships once, the browser caches it forever, and
each call sends just the ~80 B ``<use>`` wrapper.

Why we keep this as a Django tag (vs. having templates inline the
``<use>`` markup directly): callers can keep writing ``{% lucide
"folder" "w-4 h-4 text-zinc-500" %}`` — no template changes, no risk
of typos in the sprite URL, and a future fallback (e.g. inline a
single hot icon when sprite-load races a first paint) lives in one
place.

Why we *don't* CDN-load ``lucide.min.js``: any in-place DOM swap
(HTMX, SSE peer-update) brings the ``<i>`` placeholder back, leaving
a single-frame blank spot until ``lucide.createIcons()`` reruns.
Server-side ``<use>`` resolves at parse time — no race, no flash.

Source dataset: ``apps/web/lucide_icons.json``, generated by
``scripts/extract_lucide.py``. The sprite is rebuilt via
``scripts/build_lucide_sprite.py`` (``make build-sprite``).

Unknown names fall back to ``DEFAULT_ICON`` so a stale or malicious
``project.icon`` value can't break a page — at worst, the user sees
the fallback glyph until they pick a real one.
"""

from __future__ import annotations

import json
from pathlib import Path
from typing import Final

from django import template
from django.templatetags.static import static
from django.utils.html import escape
from django.utils.safestring import mark_safe

register = template.Library()

# Resolve the JSON file once at module import. Used as the source of
# truth for ``has_icon`` (the form validator) and for the
# "name resolves to itself or to ``DEFAULT_ICON``" fallback inside
# the tag.
_ICONS_PATH: Final[Path] = Path(__file__).resolve().parent.parent / "lucide_icons.json"
_ICONS: Final[dict[str, str]] = json.loads(_ICONS_PATH.read_text())

DEFAULT_ICON: Final[str] = "circle-dashed"

# Static-files URL of the sprite. Resolved lazily inside the tag so
# Django's static handlers (collectstatic, ManifestStaticFilesStorage)
# can swap in a hashed filename in production — the same way every
# other ``{% static %}`` reference works.
_SPRITE_PATH: Final[str] = "sprites/lucide.svg"


@register.simple_tag
def lucide(name: str, css_class: str = "w-4 h-4") -> str:
    """Render a sprite-backed Lucide SVG.

    Args:
        name: Icon slug, e.g. ``"folder"``. Unknown slugs fall back
            to :data:`DEFAULT_ICON` so the template still renders.
        css_class: Tailwind / custom classes for sizing + colour.
            Defaults to ``"w-4 h-4"`` (16×16 currentColor).

    Returns:
        Safe SVG markup ready to drop into a template. The ``<symbol>``
        in the sprite carries the Lucide defaults (``fill="none"``,
        ``stroke="currentColor"``, ``stroke-width="2"``, …) so the
        wrapper stays minimal: ``class`` + ``viewBox`` + ``<use>``.
    """
    resolved = name if name in _ICONS else DEFAULT_ICON
    sprite_url = static(_SPRITE_PATH)
    safe_class = escape(css_class)
    return mark_safe(
        f'<svg class="{safe_class}" viewBox="0 0 24 24" aria-hidden="true">'
        f'<use href="{sprite_url}#lu-{resolved}"/>'
        f"</svg>",
    )


def has_icon(name: str) -> bool:
    """Return whether ``name`` exists in the loaded icon set.

    Useful for forms that accept user-entered icon slugs — validate
    server-side instead of trusting the picker UI alone.
    """
    return name in _ICONS
