# Generated by Django 5.1.15 on 2026-05-15 15:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Workspace",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(help_text="Display name of the workspace", max_length=120)),
                (
                    "slug",
                    models.SlugField(
                        help_text="URL-safe identifier; lowercase letters, digits, hyphens", max_length=60, unique=True
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, help_text="When the workspace was created")),
                (
                    "owner",
                    models.ForeignKey(
                        help_text="User who owns this workspace. Exactly one owner per workspace; transfer to change",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="owned_workspaces",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="WorkspaceMember",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "role",
                    models.CharField(
                        choices=[("owner", "Owner"), ("admin", "Admin"), ("member", "Member")],
                        default="member",
                        help_text="Role within the workspace; controls what the user can do",
                        max_length=10,
                    ),
                ),
                (
                    "joined_at",
                    models.DateTimeField(auto_now_add=True, help_text="When the user was added to the workspace"),
                ),
                (
                    "user",
                    models.ForeignKey(
                        help_text="User being granted access to the workspace",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="workspace_memberships",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "workspace",
                    models.ForeignKey(
                        help_text="Workspace this membership belongs to",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="memberships",
                        to="workspaces.workspace",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="workspace",
            name="members",
            field=models.ManyToManyField(
                help_text="Users with access to the workspace, with their role",
                related_name="workspaces",
                through="workspaces.WorkspaceMember",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddConstraint(
            model_name="workspacemember",
            constraint=models.UniqueConstraint(
                fields=("user", "workspace"), name="workspaces_member_unique_user_workspace"
            ),
        ),
    ]
