# Generated by Django 5.1.15 on 2026-05-17 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("workspaces", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="workspace",
            options={"verbose_name": "Workspace", "verbose_name_plural": "Workspaces"},
        ),
        migrations.AlterModelOptions(
            name="workspacemember",
            options={"verbose_name": "Workspace member", "verbose_name_plural": "Workspace members"},
        ),
        migrations.AddField(
            model_name="workspace",
            name="auto_archive_done_after_days",
            field=models.PositiveIntegerField(
                blank=True,
                default=30,
                help_text="Auto-archive policy: done tasks whose updated_at is older than this many days are archived by the daily archive_stale_done_tasks command. Set to NULL to disable auto-archive for this workspace. Manual archive/unarchive still works regardless",
                null=True,
            ),
        ),
    ]
