# Generated by Django 5.1.15 on 2026-05-19 17:53

import apps.workspaces.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workspaces', '0002_workspace_auto_archive_setting'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkspaceInvite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(help_text='Email address of the invitee; pre-filled and locked at signup', max_length=254)),
                ('role', models.CharField(choices=[('admin', 'Admin'), ('member', 'Member')], default='member', help_text='Workspace role granted to the new member; never grants Owner', max_length=10)),
                ('token', models.CharField(help_text='URL-safe one-use token included in the invite link', max_length=64, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='When the invite was generated')),
                ('expires_at', models.DateTimeField(default=apps.workspaces.models._default_invite_expiry, help_text='When the token stops accepting signups; defaults to created_at + 7 days')),
                ('accepted_at', models.DateTimeField(blank=True, help_text='When the invite was consumed; non-null means the token can no longer be used', null=True)),
                ('created_by', models.ForeignKey(blank=True, help_text='Admin who sent the invite; SET_NULL preserves the audit trail if they leave', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sent_workspace_invites', to=settings.AUTH_USER_MODEL)),
                ('workspace', models.ForeignKey(help_text='Workspace the invitee joins on accepting', on_delete=django.db.models.deletion.CASCADE, related_name='invites', to='workspaces.workspace')),
            ],
            options={
                'verbose_name': 'Workspace invite',
                'verbose_name_plural': 'Workspace invites',
                'ordering': ['-created_at'],
            },
        ),
    ]
