# Generated by Django 5.1.15 on 2026-05-22 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workspaces', '0003_workspaceinvite'),
    ]

    operations = [
        migrations.AddField(
            model_name='workspace',
            name='wip_limits',
            field=models.JSONField(blank=True, default=dict, help_text='Workspace-wide WIP-limit policy as {"mode": off|personal|column, "limits": {status_key: max}}. personal = each member may hold at most max tasks in that status across the whole workspace; column = the kanban column holds at most max cards for the team. Empty / off disables it'),
        ),
    ]
