# Generated by Django 5.1.15 on 2026-05-22 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workspaces', '0004_workspace_wip_limits'),
    ]

    operations = [
        migrations.AddField(
            model_name='workspace',
            name='cycle_settings',
            field=models.JSONField(blank=True, default=dict, help_text='Cadence config for workspace cycles as {"enabled": bool, "length_weeks": int, "start_date": "YYYY-MM-DD"}. start_date is the anchor of cycle 1; subsequent cycles roll automatically every length_weeks. Empty / disabled hides cycles'),
        ),
    ]
