# Generated by Django 5.1.15 on 2026-05-23 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workspaces', '0005_workspace_cycle_settings'),
    ]

    operations = [
        migrations.AddField(
            model_name='workspace',
            name='allow_member_announcements',
            field=models.BooleanField(default=False, help_text='When true, any workspace member can broadcast an announcement to everyone; when false (default), only owners and admins can'),
        ),
        migrations.AlterField(
            model_name='workspace',
            name='cycle_settings',
            field=models.JSONField(blank=True, default=dict, help_text='Cadence config for workspace cycles as {"enabled": bool, "length_weeks": int, "start_date": "YYYY-MM-DD", "auto_rollover": bool}. start_date is the anchor of cycle 1; subsequent cycles roll automatically every length_weeks. auto_rollover moves unfinished tasks into the next cycle when one completes. Empty / disabled hides cycles'),
        ),
    ]
