# Generated by Django 5.1.15 on 2026-05-31 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workspaces', '0006_workspace_allow_member_announcements_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='workspace',
            name='required_fields',
            field=models.JSONField(blank=True, default=dict, help_text='Per-transition required-field policy as {"leave_todo": {"assignee": bool, "priority": bool}, "enter_in_review": {"description": bool}}. Each true flag blocks the transition with a toast until the field is set. Empty / missing flags let the transition through (current default)'),
        ),
    ]
