# Generated by Django 5.1.15 on 2026-05-31 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workspaces', '0007_workspace_required_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='workspace',
            name='member_defaults',
            field=models.JSONField(blank=True, default=dict, help_text='Defaults applied to fresh invitees as {"default_role": "admin|member", "auto_add_to_all_projects": bool}. ``default_role`` pre-selects the role in the invite form; ``auto_add_to_all_projects`` adds the user to every existing project on invite acceptance. Empty = no defaults applied'),
        ),
    ]
