# Generated by Django 5.1.15 on 2026-09-04 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workspaces', '0008_workspace_member_defaults'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workspace',
            name='slug',
            field=models.SlugField(help_text="URL-safe identifier; lowercase letters, digits, hyphens. Immutable once set — it is the workspace's segment in every URL, and changing it would break links already in the wild (ADR 0031). Renaming a workspace changes name only", max_length=60, unique=True),
        ),
    ]
