# Generated by Django 5.1.15 on 2026-10-02 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workspaces', '0009_alter_workspace_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='workspace',
            name='epics_enabled',
            field=models.BooleanField(default=True, help_text='When true (default), the workspace can group tasks under epics: the Epics tab, the Epic row on a task and the pickers appear. Turning it off hides the feature and refuses new epics; existing epics keep their tasks and come back on re-enable'),
        ),
    ]
