# Generated by Django 5.1.15 on 2026-10-08 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workspaces', '0010_epics_toggle'),
    ]

    operations = [
        migrations.AddField(
            model_name='workspace',
            name='ready_enabled',
            field=models.BooleanField(default=True, help_text='When true (default), the workspace keeps the Ready column — the replenishment buffer between the backlog and active work. Turning it off moves every ready task to planned and refuses new ones; turning it back on does not bring them back'),
        ),
    ]
