# Generated by Django 5.1.15 on 2026-05-23 15:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TelegramAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chat_id', models.BigIntegerField(help_text='Telegram chat id the bot sends messages to; unique per linked user', unique=True)),
                ('username', models.CharField(blank=True, help_text='Telegram @username at link time, for display. Optional (users may have none)', max_length=64)),
                ('enabled', models.BooleanField(default=True, help_text='Whether to deliver notifications to this chat; user toggle, defaults on when linked')),
                ('linked_at', models.DateTimeField(auto_now_add=True, help_text='When the account was linked')),
                ('user', models.OneToOneField(help_text='Acta user this Telegram chat is linked to', on_delete=django.db.models.deletion.CASCADE, related_name='telegram', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Telegram account',
                'verbose_name_plural': 'Telegram accounts',
            },
        ),
    ]
