# Generated by Django 5.1.15 on 2026-05-23 16:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telegram', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TelegramLinkToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(help_text='Random URL-safe token embedded in the t.me start deep link', max_length=64, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='When the token was minted; resolution rejects it past the TTL')),
                ('user', models.ForeignKey(help_text='User the token links the next /start to', on_delete=django.db.models.deletion.CASCADE, related_name='telegram_link_tokens', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Telegram link token',
                'verbose_name_plural': 'Telegram link tokens',
            },
        ),
    ]
