# Generated by Django 5.1.15 on 2026-05-23 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telegram', '0002_telegramlinktoken'),
    ]

    operations = [
        migrations.AddField(
            model_name='telegramaccount',
            name='muted_kinds',
            field=models.JSONField(blank=True, default=list, help_text='Notification kinds (Notification.Kind values) NOT delivered here; empty = all kinds sent'),
        ),
        migrations.AlterField(
            model_name='telegramaccount',
            name='enabled',
            field=models.BooleanField(default=True, help_text='Master switch for delivery to this chat; user toggle, defaults on when linked'),
        ),
    ]
