# Generated by Django 5.1.15 on 2026-05-23 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telegram', '0003_telegramaccount_muted_kinds_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TelegramMessageTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(help_text='Notification kind this template applies to (one row per kind)', max_length=20, unique=True)),
                ('body', models.TextField(help_text='Message text with {placeholder} tokens: {actor} {task} {slug} {title} {preview}. Empty falls back to the built-in default for this kind')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='When the template was last edited')),
            ],
            options={
                'verbose_name': 'Telegram message template',
                'verbose_name_plural': 'Telegram message templates',
            },
        ),
    ]
