# Generated by Django 5.1.15 on 2026-05-31 08:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telegram', '0004_telegrammessagetemplate'),
    ]

    operations = [
        migrations.AddField(
            model_name='telegramaccount',
            name='quiet_hours_enabled',
            field=models.BooleanField(default=False, help_text='When on, notifications fired inside the start/end window are queued instead of delivered live; one consolidated digest goes out the first scheduler tick after the window closes'),
        ),
        migrations.AddField(
            model_name='telegramaccount',
            name='quiet_hours_end',
            field=models.TimeField(blank=True, help_text='Local time the quiet window closes (e.g. 08:00). When end < start the window wraps past midnight', null=True),
        ),
        migrations.AddField(
            model_name='telegramaccount',
            name='quiet_hours_start',
            field=models.TimeField(blank=True, help_text='Local time the quiet window opens (e.g. 18:00). Server TZ for MVP; per-user TZ deferred', null=True),
        ),
        migrations.CreateModel(
            name='TelegramQueuedNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(help_text='Notification kind (Notification.Kind value); kept for (task_id, kind) dedupe', max_length=20)),
                ('task_id', models.IntegerField(blank=True, help_text='Source task id when the notification was task-scoped; null otherwise. Same-task chatter is de-duplicated by (task_id, kind), keeping the latest', null=True)),
                ('body', models.TextField(help_text="Rendered Telegram message body frozen at queue time (HTML, bot's parse_mode)")),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='When the row was queued; also drives chronological order in the digest')),
                ('delivered_at', models.DateTimeField(blank=True, help_text='When the digest including this row went out; null while still pending', null=True)),
                ('account', models.ForeignKey(help_text='Account whose quiet hours queued this row', on_delete=django.db.models.deletion.CASCADE, related_name='queued_notifications', to='telegram.telegramaccount')),
            ],
            options={
                'verbose_name': 'Telegram queued notification',
                'verbose_name_plural': 'Telegram queued notifications',
                'ordering': ['created_at'],
                'indexes': [models.Index(fields=['account', 'delivered_at'], name='telegram_te_account_a08d77_idx')],
            },
        ),
    ]
