# Generated by Django 5.1.15 on 2026-06-10 08:12

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projects', '0007_project_notify_members_only'),
        ('tasks', '0013_task_occurrence_date_task_recurrence_and_more'),
        ('workspaces', '0008_workspace_member_defaults'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Meeting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Short title shown in the calls list and on linked tasks', max_length=200)),
                ('happened_at', models.DateTimeField(help_text='When the call took place')),
                ('duration_minutes', models.PositiveIntegerField(help_text='Time spent on the call, in minutes; the whole-meeting duration that rolls up to linked tasks', validators=[django.core.validators.MinValueValidator(1)])),
                ('notes', models.TextField(blank=True, help_text='Free-form Markdown notes or outcomes from the call')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='When the meeting record was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='When the meeting record was last edited')),
                ('created_by', models.ForeignKey(blank=True, help_text='Who logged the meeting; null if that user was later deleted', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='meetings_created', to=settings.AUTH_USER_MODEL)),
                ('participants', models.ManyToManyField(blank=True, help_text='Workspace members who took part in the call', related_name='meetings_attended', to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(blank=True, help_text='Optional project tag; cleared (not deleted) if the project is removed', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='meetings', to='projects.project')),
                ('tasks', models.ManyToManyField(blank=True, help_text="Tasks this call relates to; the meeting appears on each linked task's detail view", related_name='meetings', to='tasks.task')),
                ('workspace', models.ForeignKey(help_text='Workspace the meeting belongs to; meetings are workspace-level and may link tasks across projects', on_delete=django.db.models.deletion.CASCADE, related_name='meetings', to='workspaces.workspace')),
            ],
            options={
                'verbose_name': 'Meeting',
                'verbose_name_plural': 'Meetings',
                'ordering': ['-happened_at'],
                'indexes': [models.Index(fields=['workspace', '-happened_at'], name='meetings_me_workspa_0d1e53_idx')],
            },
        ),
    ]
