# Generated by Django 5.1.15 on 2026-05-20 07:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('activity', '0002_alter_activitylog_options'),
        ('comments', '0002_alter_comment_options'),
        ('tasks', '0004_task_blocks_task_related'),
        ('workspaces', '0003_workspaceinvite'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('mention', 'Mention'), ('assigned', 'Assigned'), ('due', 'Due soon'), ('comment', 'Comment'), ('status_change', 'Status change'), ('priority_change', 'Priority change'), ('system', 'System')], help_text='Notification category, drives the type-icon and the inbox filter chips', max_length=20)),
                ('preview', models.TextField(blank=True, default='', help_text='Denormalized snippet shown in the inbox list (comment body or task title)')),
                ('payload', models.JSONField(blank=True, default=dict, help_text='Event-specific details as JSON: status diff, priority tint, and so on')),
                ('is_read', models.BooleanField(default=False, help_text='Whether the recipient has read the notification')),
                ('read_at', models.DateTimeField(blank=True, help_text='When the recipient marked the notification read', null=True)),
                ('archived_at', models.DateTimeField(blank=True, help_text='When the recipient archived the notification out of the inbox', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='When the notification was created. Always sort the inbox by this column')),
                ('activity', models.ForeignKey(blank=True, help_text='Activity-log row this notification was fanned out from, if any', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notifications', to='activity.activitylog')),
                ('actor', models.ForeignKey(blank=True, help_text='User whose action triggered the notification. Null for system events', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notifications_sent', to=settings.AUTH_USER_MODEL)),
                ('comment', models.ForeignKey(blank=True, help_text='Comment that triggered the notification, for comment and mention previews', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notifications', to='comments.comment')),
                ('recipient', models.ForeignKey(help_text='User this notification is delivered to', on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
                ('task', models.ForeignKey(blank=True, help_text='Task the notification is about, if any. Null-safe so the row survives task deletion', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notifications', to='tasks.task')),
                ('workspace', models.ForeignKey(help_text='Workspace the notification belongs to. Denormalized for fast per-user filtering', on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='workspaces.workspace')),
            ],
            options={
                'verbose_name': 'Notification',
                'verbose_name_plural': 'Notifications',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['recipient', 'archived_at', 'is_read', '-created_at'], name='notificatio_recipie_1c70d9_idx'), models.Index(fields=['recipient', '-created_at'], name='notificatio_recipie_a972ce_idx')],
            },
        ),
    ]
