# Generated by Django 5.1.15 on 2026-05-20 17:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
        ('projects', '0003_add_project_icon_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='project_update',
            field=models.ForeignKey(blank=True, help_text='Project update this notification is about, for project_update kind', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notifications', to='projects.projectupdate'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='kind',
            field=models.CharField(choices=[('mention', 'Mention'), ('assigned', 'Assigned'), ('due', 'Due soon'), ('comment', 'Comment'), ('status_change', 'Status change'), ('priority_change', 'Priority change'), ('project_update', 'Project update'), ('system', 'System')], help_text='Notification category, drives the type-icon and the inbox filter chips', max_length=20),
        ),
    ]
