# Generated by Django 5.1.15 on 2026-05-23 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0003_alter_notification_kind'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='kind',
            field=models.CharField(choices=[('mention', 'Mention'), ('assigned', 'Assigned'), ('due', 'Due soon'), ('comment', 'Comment'), ('status_change', 'Status change'), ('priority_change', 'Priority change'), ('project_update', 'Project update'), ('cycle', 'Cycle'), ('announcement', 'Announcement'), ('system', 'System')], help_text='Notification category, drives the type-icon and the inbox filter chips', max_length=20),
        ),
    ]
