# Generated by Django 5.1.15 on 2026-06-10 13:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meetings', '0001_initial'),
        ('notifications', '0004_alter_notification_kind'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='meeting',
            field=models.ForeignKey(blank=True, help_text='Meeting this notification is about, for meeting kind', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notifications', to='meetings.meeting'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='kind',
            field=models.CharField(choices=[('mention', 'Mention'), ('assigned', 'Assigned'), ('due', 'Due soon'), ('comment', 'Comment'), ('status_change', 'Status change'), ('priority_change', 'Priority change'), ('project_update', 'Project update'), ('meeting', 'Meeting'), ('cycle', 'Cycle'), ('announcement', 'Announcement'), ('system', 'System')], help_text='Notification category, drives the type-icon and the inbox filter chips', max_length=20),
        ),
    ]
